INSERT INTO
  users (
    user_level_id,
    email,
    password,
    preferred_alias,
    first_name,
    last_name,
    gender
  )
VALUES
  (
    1,
    'jack@nowhere.com',
    '2b$10$5ITbTbijOMvh0tpWwtMSKupRDFr/Li672NGVEFxI1Bh35d3eFE8Jy',
    'Jack',
    'Jack',
    'Mindster',
    'male'
  ),
  (
    5,
    'george@abc.com',
    '2b$10$5ITbTbijOMvh0tpWwtMSKupRDFr/Li672NGVEFxI1Bh35d3eFE8Jy',
    'MonkeyGeorge',
    'George',
    'Maul',
    'male'
  ),
  (
    6,
    'guest@abc.com',
    '2b$10$5ITbTbijOMvh0tpWwtMSKupRDFr/Li672NGVEFxI1Bh35d3eFE8Jy',
    'na',
    'Guest',
    'Star',
    'female'
  ),
  (
    5,
    'bye@abc.com',
    'abc',
    'ByeStander',
    'Bye',
    'Bye',
    'female'
  );
